# Generated by Django 3.2.5 on 2021-08-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_teammate_projectteam_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectteam',
            old_name='Members',
            new_name='teammate',
        ),
    ]
