# Generated by Django 3.2.5 on 2021-08-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-do'), ('In-progress', 'In-progress'), ('Done', 'Done'), ('Declined', 'Declined'), ('Ready For Testing', 'Ready For Testing'), ('Code Review', 'Code Review'), ('Testing in-progress', 'Testing in-progress')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Improvement', 'Improvement'), ('New Feature', 'New Feature'), ('Story', 'Story'), ('Task', 'Task'), ('Epic', 'Epic')], max_length=30),
        ),
    ]
