# Generated by Django 3.2.5 on 2021-12-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210830_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.sprint'),
        ),
    ]
