# Generated by Django 3.2.5 on 2021-07-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_email',
        ),
    ]
