# Generated by Django 3.2.5 on 2021-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_role_user_designation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Designation",
            new_name="designation",
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
