# Generated by Django 3.2.5 on 2021-11-23 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210727_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntermediateUserTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.technology')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='technologies',
            field=models.ManyToManyField(through='accounts.IntermediateUserTech', to='accounts.Technology'),
        ),
    ]
