# Generated by Django 3.2.5 on 2021-07-23 15:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
